### ISSUE TITLE
(Vaadin 15.0.4) Missing @JsModule

### ISSUE THREAD

**Issue by Tonne-TM** [mdre/FlowSubwindow#1]
I tried using the widget but at runtime i get the following error:

```
Caused by: java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'sub-windows-desktop' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:140) ~[flow-server-3.0.5.jar:3.0.5]
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:200) ~[flow-server-3.0.5.jar:3.0.5]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:91) ~[flow-server-3.0.5.jar:3.0.5]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:88) ~[flow-server-3.0.5.jar:3.0.5]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103) ~[flow-server-3.0.5.jar:3.0.5]
	at com.awesomecontrols.subwindow.SubWindowDesktop.<init>(SubWindowDesktop.java:49) ~[flowsubwindow-1.0.3.jar:1.0.3]
	at de.izanami.webapp.ui.layout.main.SubWindowView.afterPropertiesSet(SubWindowView.java:103) ~[classes/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.3.RELEASE.jar:5.2.3.RELEASE]
	... 130 common frames omitted


```

Is there support for Vaadin 15 planned? Or is this error not caused by the version?

**Comment by Tonne-TM** [comment]
I used `vaadin.whitelisted-packages` Packages. That caused the problem.
