### ISSUE TITLE
Error: No element with id='desktop' in sub-windows-desktop.js

### ISSUE THREAD

**Issue by Tonne-TM** [mdre/FlowSubwindow#2]
I get the following error when trying to add SubWindowDesktop to a page:

```
Caused by: java.lang.IllegalStateException: There is no element with id='desktop' in the template file './sub-window/sub-windows-desktop.js'. Cannot map it using @Id
	at com.vaadin.flow.component.polymertemplate.IdCollector.collectedInjectedId(IdCollector.java:106) ~[flow-server-3.0.5.jar:3.0.5]
	at com.vaadin.flow.component.polymertemplate.IdCollector.lambda$collectInjectedIds$1(IdCollector.java:78) ~[flow-server-3.0.5.jar:3.0.5]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at com.vaadin.flow.component.polymertemplate.IdCollector.collectInjectedIds(IdCollector.java:78) ~[flow-server-3.0.5.jar:3.0.5]
	at com.vaadin.flow.component.polymertemplate.IdCollector.collectInjectedIds(IdCollector.java:67) ~[flow-server-3.0.5.jar:3.0.5]
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:215) ~[flow-server-3.0.5.jar:3.0.5]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:91) ~[flow-server-3.0.5.jar:3.0.5]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:88) ~[flow-server-3.0.5.jar:3.0.5]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103) ~[flow-server-3.0.5.jar:3.0.5]
	at com.awesomecontrols.subwindow.SubWindowDesktop.<init>(SubWindowDesktop.java:49) ~[flowsubwindow-1.0.3.jar:1.0.3]
```

Any idea how to fix this?

**Comment by lavdev** [comment]
I'm get this error too.. some idea already how to fix it ?

**Comment by mdre** [comment]
Hi! 
Well, what I see is that the mvn version does not build the component if you not use the production profile. So you need run:

mvn jetty:run -Pproduction

to get it work.
